remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: true
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Data analyst
  - Data Scientist
  - Machine learning
  - Software engineer

locations:
  - Gurgaon Rural, Haryana, India
  - New Delhi, Delhi, India
  - India
  - Canada
  - United Kingdom
  - Europe
  - United States of America

apply_once_at_company: false

distance: 100

company_blacklist:
  - CodSoft
  - CodeClause
  - Bharat Intern
  - Prodology
  - Code Alpha
  - Encryptix
  - Oasis InfoByte
  - InternPe
  - CodeEvo
  - OctaNet
  - Prodigy Info Tech
  - Learn Smasher
  - CodersCave

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: gemini
llm_model: 'gemini-1.5-pro'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
